export const imgs = [
	{
		src: 'https://th.wallhaven.cc/small/qz/qz13pl.jpg'
	},
	{
		src: 'https://th.wallhaven.cc/small/kx/kxpkmm.jpg'
	},
	{
		src: 'https://th.wallhaven.cc/small/jx/jxm1mw.jpg'
	},
	{
		src: 'https://th.wallhaven.cc/small/jx/jxmvkp.jpg'
	},
	{
		src: 'https://th.wallhaven.cc/small/p9/p9qj59.jpg'
	},
	{
		src: 'https://th.wallhaven.cc/small/x6/x6v2oz.jpg'
	},
	{
		src: 'https://th.wallhaven.cc/small/we/we2llx.jpg'
	},
	{
		src: 'https://th.wallhaven.cc/small/x6/x6vzjl.jpg'
	},
	{
		src: 'https://th.wallhaven.cc/small/2y/2yr2vm.jpg'
	},
	{
		src: 'https://th.wallhaven.cc/small/qz/qz1oy5.jpg'
	},
	{
		src: 'https://th.wallhaven.cc/small/we/we276p.jpg'
	},
	{
		src: 'https://th.wallhaven.cc/small/5g/5g26o9.jpg'
	},
	{
		src: 'https://th.wallhaven.cc/small/p9/p9qwvj.jpg'
	},
	{
		src: 'https://th.wallhaven.cc/small/2y/2yrw39.jpg'
	},
]